const data = [
  {
    nam: "Embroidered Lawn  a! Suit",
    id: 0,
    Price: 5000,
    Feature: true,
    stock: 8,
    stockValue: 10,
  },
  {
    nam: "a! Suit",
    id: 1,
    Price: 5000,
    Feature: true,
    stock: 8,
    stockValue: 10,
  },  {
    nam: "Embroidered Lawn  a! Suit",
    id: 0,
    Price: 5000,
    Feature: true,
    stock: 8,
    stockValue: 10,
  },
  {
    nam: "a! Suit",
    id: 1,
    Price: 5000,
    Feature: true,
    stock: 8,
    stockValue: 10,
  },  {
    nam: "Embroidered Lawn  a! Suit",
    id: 0,
    Price: 5000,
    Feature: true,
    stock: 8,
    stockValue: 10,
  },
  {
    nam: "a! Suit",
    id: 1,
    Price: 5000,
    Feature: true,
    stock: 8,
    stockValue: 10,
  },  {
    nam: "Embroidered Lawn  a! Suit",
    id: 0,
    Price: 5000,
    Feature: true,
    stock: 8,
    stockValue: 10,
  },
  {
    nam: "a! Suit",
    id: 1,
    Price: 5000,
    Feature: true,
    stock: 8,
    stockValue: 10,
  },  {
    nam: "Embroidered Lawn  a! Suit",
    id: 0,
    Price: 5000,
    Feature: true,
    stock: 8,
    stockValue: 10,
  },
  {
    nam: "a! Suit",
    id: 1,
    Price: 5000,
    Feature: true,
    stock: 8,
    stockValue: 10,
  },
];
export default data;
